### ISSUE TITLE
txt文件缺失

### ISSUE THREAD

**Issue by woshuaizuishuai** [xzy-xzy/MLPSB-Parser#1]
请问里面rellog.txt和poslog.txt是数据文件有，还是自己生成的？

**Comment by xzy-xzy** [comment]
rellog.txt和poslog.txt分别存放了该树库里可能出现的依存关系和词性，已经生成好了放在对应树库文件夹下，所有树库语料都可以在readme里提供的链接中下载

**Comment by xzy-xzy** [comment]
如果已经放置下载的语料仍提示找不到，可能是放置位置不对，请参考更新后readme中给出的目录结构说明
